let StrikeList = [
    {Catagory:"GOOD",
    Reason:"No Strike Avalable",
    StrikeWord:"N/A",
    StrikeCode:"0"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike for hitting his classmate",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"02"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike for plaing illigal card games in school ",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"03"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike for bringing mobile phone in school please meet with vice-principal for more info",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"04"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike since he violated ICT class time",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"05"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike Math teacher found abusive drugs in his bag",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"06"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike for abusing a girl during class time ",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"07"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike for Abusive behavior with teacher",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"08"},
    {Catagory:"STRIKE!",
    Reason:"Currently got a strike for missing class in a excessive amount",
    Recomendation:"Please take care of your child as it's high time",
    StrikeWord:"RULE-CODE",
    StrikeCode:"09"},
    {Catagory:"ACCOUNT!",
    Reason:"Acount is frozen due to Due payment ",
    Recomendation:"please complete your child's due payment",
    StrikeWord:"DETAILS-",
    StrikeCode:"CLICK HERE"}
]